#
# Module manifest for module 'PowerShell.Template'
#
# Generated by: Rusty Hann
#
# Generated on: 02/3/2020
#

@{
    # Version number of this module.
    ModuleVersion = '1.0.0.0'

    # ID used to uniquely identify this module
    GUID = 'c158b7d2-58e0-4d91-8da0-030dc6612c21'

    # Author of this module
    Author = 'Rusty Hann'

    # Company or vendor of this module
    CompanyName = 'rustyhann.com'

    # Copyright statement for this module
    Copyright = '(c) 2020 rustyhann.com. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Provides a PowerShell Module Template.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Script module or binary module file associated with this manifest.
    RootModule = 'PowerShell.Template.psm1'

    # Functions to export from this module
    FunctionsToExport = '*'

    # Cmdlets to export from this module
    CmdletsToExport = '*'
}